"""add images field and unique

Revision ID: 6395b716ef8e
Revises: ffc237110699
Create Date: 2022-12-30 21:44:42.628135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6395b716ef8e'
down_revision = 'ffc237110699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.drop_index('ix_information_uuid')
        batch_op.create_index(batch_op.f('ix_information_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=100), nullable=True))
        batch_op.drop_index('ix_users_uuid')
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)
        batch_op.create_index('ix_users_uuid_email', ['uuid', 'email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_uuid_email')
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.create_index('ix_users_uuid', ['uuid'], unique=False)
        batch_op.drop_column('image_name')

    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_information_uuid'))
        batch_op.create_index('ix_information_uuid', ['uuid'], unique=False)

    # ### end Alembic commands ###
