"""add information table

Revision ID: ffc237110699
Revises: 3fd7abedd20e
Create Date: 2022-12-30 17:49:47.709355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc237110699'
down_revision = '3fd7abedd20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information',
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('user_uuid', sa.CHAR(length=36), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('post_code', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_information_user_uuid'), ['user_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_information_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_information_uuid'))
        batch_op.drop_index(batch_op.f('ix_information_user_uuid'))

    op.drop_table('information')
    # ### end Alembic commands ###
